### PR TITLE
Fixed the 'Learn More' button behaviour

### LINKED ISSUE #11: Fix the "learn more" behavior
Current behavior:
screenshot from 2018-09-26 16-32-13

Expected behavior: When you click learn more, in the main page, you page should scroll and put the "I do my magic in" in the middle of the page!

screenshot from 2018-09-26 16-32-35

### PR DESCRIPTION
**Pull request by himankpathak**
### Description of the Change

When you click on "learn more" button, the page should jump to "Tell us a bit about yourself" section and also the section should be at the center of the page.
Fixed this issue by using Element.scrollIntoView() method. [Learn more]()

### Benefits

The home page now scrolls down smoothly until the "Tell us a bit about yourself" section reaches the center of the page.

### Verification Process

Verified that the changes work in Firefox and Chrome as expected.

### Applicable Issues

Closes #11

### CODE REVIEW

File: src/routes/Home/components/Home.tsx [hunk 1]
```diff
@@ -35,8 +35,11 @@ export default class Home extends React.PureComponent<IHomeProps,{
     this.props.updateType();
   }
 
-public onClick=()=> {
-  this.setState(state => ({ focusSelect: !state.focusSelect}))
```
Comment (alexdor) [inline src/routes/Home/components/Home.tsx]: This line is required in order to focus the input box, if this line breaks the scrolling you can try using a setTimeout with 100ms : )

**Comment by alexdor** [comment]
Looks good @himankpathak : )
